{{- if .Values.route.enabled -}}
{{- $fullName := include "starter-kit.fullname" . -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}-health
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  #host: *.appdev-cloudnative-ocp43-6fb0b86391cd68c8282858623a1dddff-0000.eu-gb.containers.appdomain.cloud
  #wildcardPolicy: Subdomain  
  path: /
  to:
    kind: Service
    name: {{ $fullName }}
  tls:
    termination: edge
{{- end }}
